name: latentstrat
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - pyarrow
  - scipy
  - scikit-learn
  - matplotlib
  - tabulate
  - pytorch
  - pip:
      - tbapy==1.3.2
      - statbotics==3.0.0
      - requests-cache
      - diskcache
      - openai>=1
      - pydantic>=2
      - python-dotenv
      - sqlmodel>=0.0.22
      - tensorboard>=2.16
      - typer
      - pytest
      - vcrpy
      - ruff
